version: "3.8"

services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  hotel-backend:
    build: ./hotel-service/backend
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/hotel-db

  api-gateway:
    build: ./api-gateway
    depends_on:
      - hotel-backend
    ports:
      - "8081:8081"
    environment:
      HOTEL_SERVICE_URL: http://hotel-backend:8080

  hotel-frontend:
    build: ./hotel-service/frontend
    depends_on:
      - api-gateway
    ports:
      - "5001:80"

  main-frontend:
    build: ./main-frontend
    depends_on:
      - api-gateway
      - hotel-frontend
    ports:
      - "3000:80"

volumes:
  mongo_data:
