package com.example.hotelservice.controller;

import com.example.hotelservice.model.Hotel;
import com.example.hotelservice.repository.HotelRepository;
import org.springframework.web.bind.annotation.*;
import java.util.List;
import java.util.stream.Collectors;

@RestController
@RequestMapping("/api/hotels")
public class HotelController {
    private final HotelRepository hotelRepository;

    public HotelController(HotelRepository hotelRepository) {
        this.hotelRepository = hotelRepository;
    }

    @GetMapping
    public List<Hotel> getAllHotels() {
        return hotelRepository.findAll();
    }

    @GetMapping("/location/{location}")
    public List<Hotel> getHotelsByLocation(@PathVariable String location) {
        return hotelRepository.findByLocation(location);
    }

    @GetMapping("/locations")
    public List<String> getLocations() {
        return hotelRepository.findAll()
            .stream()
            .map(Hotel::getLocation)
            .distinct()
            .collect(Collectors.toList());
    }

    @GetMapping("/search")
    public List<Hotel> searchHotels(@RequestParam(required = false) String area,
                                    @RequestParam(required = false) String checkin,
                                    @RequestParam(required = false) String checkout) {
        // For now, only filter by area. You can add date logic if Hotel has availability info.
        return hotelRepository.findAll().stream()
            .filter(hotel -> area == null || hotel.getLocation().equalsIgnoreCase(area))
            .collect(Collectors.toList());
    }

    @GetMapping("/{id}")
    public Hotel getHotelById(@PathVariable String id) {
        return hotelRepository.findById(id).orElse(null);
    }

    @PostMapping
    public Hotel addHotel(@RequestBody Hotel hotel) {
        // id will be auto-generated by MongoDB if not provided
        return hotelRepository.save(hotel);
    }
}